# playbook file for Nginx and PhpFpm hosts
---
- hosts: all
  vars:
    - remote_login: "ubuntu"
    ## Users and Groups
    - sudo_group: 'superusers'
    - users:
      - user1
      - user2
  #
  gather_facts: no
  remote_user: "{{ remote_login }}"
  become: yes
  become_method: sudo
  #become_user: root

  tasks:
  ## Remove Users
  - name: Ubuntu(22) - Undeploy - STEP01 - Remove users
    user:
      name: "{{ item }}"
      state: absent
      remove: true
    with_items:
      - "{{ users }}"

  ## Remove User Group
  - name: Ubuntu(22) - Undeploy - STEP02 - Remove user group
    group:
      name: "{{ sudo_group }}"
      state: absent

  ## Remove Group from Sudoers config
  - name: Ubuntu(22) - STEP03 - Revoke sudo permissions for "superusers" group
    lineinfile:
      dest: "/etc/sudoers"
      state: present
      regexp: "^%superusers"
      line: "# %wheel ALL=(ALL) NOPASSWD: ALL"

##=
##  Result check after playbook aplly on remote host
##
##    $ id user1                                    ## id: ‘user1’: no such user
##    $ id user2                                    ## id: ‘user2’: no such user
##    $ ls /home                                    ## devops  ubuntu
##    $ cat /etc/passwd | grep user1                ## ..blank
##    $ cat /etc/passwd | grep user2                ## ..blank
##    $ cat /etc/grroup | grep superusers           ## ..blank
##    $ sudo cat /etc/sudoers | grep superusers     ## ..blank
##
